test:
  adapter: test

development:
  adapter: redis
  url: "redis://localhost:6379/1"
  channel_prefix: <%= File.basename(File.expand_path('../..', __FILE__)).split('.').first %>_development

production:
  adapter: redis
  url: "redis://localhost:6379/1"
  channel_prefix: <%= File.basename(File.expand_path('../..', __FILE__)).split('.').first %>_production
